version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2300:2300'
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SIDEKIQ_CONCURRENCY=5
    volumes:
      - ./app:/app

  db:
    image: postgres:14
    restart: always
    ports:
      - '5430:5432'
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=feedpuls_dev
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - '6380:6379'
    volumes:
      - ./redis-data:/data

  sidekiq:
    build:
      context: .
#      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SIDEKIQ_CONCURRENCY=5

    command: bundle exec sidekiq -r ./config/sidekiq.rb
