services:
  app:
    container_name: feedpulse-worker
    build:
      context: .
      dockerfile: app.dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - dev-network
    ports:
      - 2301:2300

networks:
  dev-network:
    external: true
    name: dev-network
