services:
  redis:
    container_name: feedpulse_redis
    image: redis
    restart: always
    networks:
      - dev-network
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  app:
    container_name: feedpulse_app
    build:
      context: .
      dockerfile: app.dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - dev-network
    ports:
      - 2301:2300

networks:
  dev-network:

volumes:
  redis-data:
