# fly.toml app configuration file generated for feedpulse on 2023-06-03T18:26:56+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "feedpulse"
primary_region = "yyz"

[processes]
  app = "hanami server --host 0.0.0.0 --port 2300"
  worker = "bundle exec sidekiq ./config/sidekiq.rb"

[http_service]
  processes = ["app"]
  internal_port = 2300
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
