openapi: 3.0.3
info:
  title: FeedPulse API
  version: 1.0.1
servers:
  - url: https://feedpulse.onrender.com/
    description: Production Server
  - url: http://localhost:2300/
    description: Test Server
paths:
  /account/register:
    post:
      summary: User Registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: User registration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      username:
                        type: string
                      email:
                        type: string
                      api_key:
                        type: string
        '409':
          description: Email or username unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
        '500':
          description: Request failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string

  /api/feeds:
    get:
      summary: Get News Items
      parameters:
        - name: page
          in: query
          description: Page number
          schema:
            type: integer
        - name: per_page
          in: query
          description: Number of items per page
          schema:
            type: integer
        - name: country
          in: query
          description: Country code
          schema:
            type: string
        - name: username
          in: query
          description: Username of user making request
          schema:
            type: string
      security:
        - ApiKeyAuth: [ ]
      responses:
        '200':
          description: News items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    snippet:
                      type: string
                    url:
                      type: string
                    source:
                      type: string
                    code:
                      type: string
                    date:
                      type: string
        '401':
          description: Missing or invalid api key
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
        '403':
          description: Invalid username or api key
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string
        '500':
          description: Request failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: string


components:
  securitySchemes:
      ApiKeyAuth:
        type: apiKey
        in: header
        name: Authorization
